### ISSUE TITLE
Remove overly specific checklist items from the merge request template - [merged]

### ISSUE THREAD

**Issue by noheton** [noheton/shepard#787]
***In GitLab by @thaase on Jul 12, 2024, 11:28 GMT+2:***

_Merges remove-checklist-items -> develop_

# Merge Request

### Checklist

- [x] The code compiles without any warnings.
- [x] I followed the [code review checklist](https://gitlab.com/dlr-shepard/shepard/-/blob/main/CONTRIBUTING.md#code-review-checklist).
- [x] The documentation has been added/updated.
- [ ] There are no `System.out.println()` statements.
- [ ] `package-lock.json` was not changed unless I added or edited dependencies.

### Related Issues

- Related #<issue number>
- Closes #<issue number>

*Migrated from GitLab: https://gitlab.com/dlr-shepard/shepard/-/merge_requests/68*

**Comment by noheton** [comment]
***In GitLab by @thaase on Jul 12, 2024, 11:28 GMT+2:***

enabled an automatic merge when all merge checks for cac247964397a19612e60012412534d2303be2dd pass

**Comment by noheton** [comment]
***In GitLab by @thaase on Jul 12, 2024, 11:28 GMT+2:***

marked the checklist item **The documentation has been added/updated.** as completed

**Comment by noheton** [comment]
***In GitLab by @thaase on Jul 12, 2024, 11:28 GMT+2:***

marked the checklist item **I followed the [code review checklist](https://gitlab.com/dlr-shepard/shepard/-/blob/main/CONTRIBUTING.md#code-review-checklist).** as completed

**Comment by noheton** [comment]
***In GitLab by @thaase on Jul 12, 2024, 11:28 GMT+2:***

marked the checklist item **The code compiles without any warnings.** as completed
